# Generated by Django 4.0.6 on 2024-04-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Autor')),
                ('foto', models.ImageField(upload_to='', verbose_name='Foto do Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Noticia')),
                ('titulo', models.CharField(default='', max_length=100, verbose_name='Titulo')),
                ('foto', models.ImageField(upload_to='', verbose_name='Capa da Noticia')),
                ('idade', models.IntegerField(verbose_name='Ano da Noticia')),
                ('texto', models.CharField(max_length=10000, verbose_name='Corpo da Noticia')),
                ('autor', models.ForeignKey(default='Nome do Autor Padrão', on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='noticias.autor', verbose_name='Autor da Noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto do Comentário')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Comentário')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.autor', verbose_name='Autor do Comentário')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia', verbose_name='Noticia')),
            ],
        ),
    ]
