# Generated by Django 4.0.6 on 2024-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
