# Generated by Django 4.0.6 on 2024-06-06 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_comentario_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Postagem'),
        ),
    ]
