# Generated by Django 4.0.6 on 2024-04-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(related_name='cursos', to='curso.disciplina', verbose_name='Disciplinas'),
        ),
    ]
