# Generated by Django 4.0.6 on 2024-04-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='conteudos',
            field=models.CharField(default='Conteúdos Programáticos Padrão', max_length=500, verbose_name='Conteúdos Programáticos'),
        ),
    ]
