# Generated by Django 4.0.6 on 2024-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_disciplina_conteudos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='gitLink',
            field=models.URLField(blank=True, null=True, verbose_name='Link Repositório GitHub'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Link Video do Youtube'),
        ),
    ]
