# Generated by Django 4.0.6 on 2024-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_banda_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banda',
            old_name='idade',
            new_name='ano_criacao',
        ),
    ]
