# Generated by Django 4.0.6 on 2024-04-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_rename_ano_criacao_banda_idade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicas',
            new_name='Musica',
        ),
    ]
