# Generated by Django 4.0.6 on 2024-04-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_rename_musicas_musica'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musica',
            new_name='Musicas',
        ),
    ]
