# Generated by Django 4.0.6 on 2024-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_rename_musica_musicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Nacionalidade'),
        ),
    ]
