# Generated by Django 4.0.6 on 2024-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_banda_nacionalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='descricao',
            field=models.CharField(default='Descrição', max_length=1000),
        ),
        migrations.AlterField(
            model_name='album',
            name='nome',
            field=models.CharField(default='Album nome', max_length=100),
        ),
    ]
