# Generated by Django 4.0.6 on 2024-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0009_album_descricao_alter_album_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicas',
            name='bibliografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='musicas',
            name='letra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
