# Generated by Django 4.0.6 on 2024-03-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='name',
            new_name='nome',
        ),
    ]
